# HTTP port
server.port=8000

# --- MySQL ---
spring.datasource.url=jdbc:postgresql://dpg-d2r9uqv5r7bs73borim0-a.singapore-postgres.render.com/velinfotech_sowx
spring.datasource.username=sridhar
spring.datasource.password=n0E4iBvvyaUSbEWXQAtmRGobLby3MjJi


# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


