# HTTP port
server.port=8000

# --- MySQL ---
spring.datasource.url=jdbc:postgresql://yaway.cen6wks0e8y1.us-east-1.rds.amazonaws.com:5432/Vel-infotech
spring.datasource.username=Yaway
spring.datasource.password=dAj1HtNx0vVwQn1AsQo3


# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
